name: MoSCoW Prioritization

on:
  pull_request_target:
    types: [ labeled, opened, unlabeled, reopened ]
  workflow_dispatch:  

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: grevend/moscow-prioritization@v2.0.1
